### ISSUE TITLE
驱动启动错误 ERROR

### ISSUE THREAD

**Issue by leehangyu** [tmplinshi/Class_DD#10]
Hi,

I am pretty happy to use your opensource.

I am having a trouble that dd64 says 驱动启动错误, (translated by google lens) which means driver error, I was wondering why this happens.

OS is windows 10 64 bit, DLL is dd64

Thank you in advance

**Comment by tmplinshi** [comment]
Hi,

Try to restart your computer. If that doesn't help, I suggest you use another library [AutoHotInterception](https://www.autohotkey.com/boards/viewtopic.php?p=289477#p289477).

**Comment by leehangyu** [comment]
Thank you for your prompt reply.

I guess this was because the host was not a pc but a laptop

This might cause the problem?
