### ISSUE TITLE
C# Class_DD

### ISSUE THREAD

**Issue by deviling124** [tmplinshi/Class_DD#2]
how to use this keypress i dont know what is that "102" my friend show me this code :<

this.Anden.key(102, 1);
this.Anden.key(102, 2);

**Comment by tmplinshi** [comment]
`102` is <kbd>F2</kbd> key.
The first parameter is DD code which corresponding to a VK code. You can use `todc` function to convert VK code to DD code.

**Comment by deviling124** [comment]
you have list of key?
Example 
102 = F2
103 = ??
104 = ??

**Comment by tmplinshi** [comment]
Download DD from the offical site http://www.ddxoft.com/, there is an executable **DD键码.exe** in the **dd81010.7z** package, which can display the DD code.

Screenshot:
![image](https://user-images.githubusercontent.com/4450756/41286863-8330b3ea-6e73-11e8-9683-103326323acf.png)

![image](https://user-images.githubusercontent.com/4450756/41286873-89115670-6e73-11e8-9500-5ec758853b23.png)

**Comment by deviling124** [comment]
thanks 100% god bless you :D
