### ISSUE TITLE
Detected to my Game

### ISSUE THREAD

**Issue by deviling124** [tmplinshi/Class_DD#3]
Can you update this because its detected For my Game :-(

**Comment by tmplinshi** [comment]
I just uploaded the lastest dll files (version: dd81010), you can do it yourself by downloading the files from http://www.ddxoft.com/. I can't do anything else since I am not the author of the DLL.

**Comment by deviling124** [comment]
who make this?you have contact?

**Comment by tmplinshi** [comment]
See the README.
