### ISSUE TITLE
possible to port with other automation tool?

### ISSUE THREAD

**Issue by sonatta09** [tmplinshi/Class_DD#7]
hi i really love this software however until my game decided to detect autohotkey.com software recently... is there any chance can you port it to Autoit?? i would love to pay you thanks

**Comment by tmplinshi** [comment]
Hi, I'm not familiar with autoit, but I will give it a try.

sonatta09 <notifications@github.com> 于 2019年3月23日周六 上午12:28写道：

**Comment by tmplinshi** [comment]
Hello, here it is: (Tested with latest AutoIt v3.3.14.5)
[DD.au3.zip](https://github.com/tmplinshi/Class_DD/files/2999565/DD.au3.zip)

My paypal is tmplinshi@gamil.com, thanks for your support.
