### ISSUE TITLE
Windows Update Broke Functionality.

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [tmplinshi/Class_DD#9]
This project was used in a YouTube video and has been very helpful, however, Windows released an update and now everyone is giving the same error. Pictures included.

![25cfe5d94bcb770dbc2d71b7c28108f0](https://user-images.githubusercontent.com/30740511/62495821-f4387f00-b7ce-11e9-8153-1c2c1d949b1f.png)
![54ac665e5f313c0dd0f0731989937398](https://user-images.githubusercontent.com/30740511/62495826-f8fd3300-b7ce-11e9-8265-a5c47748ed09.png)

**Comment by murbong** [comment]
I also have this problem. any solution?

**Comment by tmplinshi** [comment]
Hi, I just updated the DD to DD94687.
